name: ${project.artifactId}
description: ${project.description}
main: ${project.mainclass}
version: ${project.version}
website: ${project.website}
softdepend: [Vault]
authors:
  - Mitsugaru
commands:
  trail:
    description: Root command for VaporTrails
    usage: /trail ? - Show help on VaporTrails
permissions:
    VaporTrails.*:
        description: Gives access to all VaporTrails commands
        children:
            VaporTrails.admin: true
            VaporTrails.effect.smoke: true
            VaporTrails.effect.ender: true
            VaporTrails.effect.thunder: true
            VaporTrails.effect.tnt: true
            VaporTrails.effect.snow: true
            VaporTrails.effect.fire: true
            VaporTrails.effect.shine: true
            VaporTrails.effect.block: true
            VaporTrails.effect.swirl: true
            VaporTrails.effect.potion.*: true
        default: op
    VaporTrails.admin:
        description: Allows user to administrate VaporTrails
        default: op
    VaporTrails.effect.smoke:
        description: Allows user to use smoke effect
        default: op
    VaporTrails.effect.ender:
        description: Allows user to use ender effect
        default: op
    VaporTrails.effect.thunder:
        description: Allows user to use thunder effect
        default: op
    VaporTrails.effect.tnt:
        description: Allows user to use tnt effect
        default: op
    VaporTrails.effect.snow:
        description: Allows user to use snow effect
        default: op
    VaporTrails.effect.fire:
        description: Allows user to use fire effect
        default: op
    VaporTrails.effect.shine:
        description: Allows user to use shine effect
        default: op
    VaporTrails.effect.block:
        description: Allows user to use make block paths
        default: op
    VaporTrails.effect.swirl:
        description: Allows user to use swirl effect
        default: op
    VaporTrails.effect.potion.pink:
        description: Allows user to use pink potion effect
        default: op
    VaporTrails.effect.potion.aqua:
        description: Allows user to use aqua potion effect
        default: op
    VaporTrails.effect.potion.gold:
        description: Allows user to use gold potion effect
        default: op
    VaporTrails.effect.potion.green:
        description: Allows user to use green potion effect
        default: op
    VaporTrails.effect.potion.red:
        description: Allows user to use red potion effect
        default: op
    VaporTrails.effect.potion.darkred:
        description: Allows user to use darkred potion effect
        default: op
    VaporTrails.effect.potion.gray:
        description: Allows user to use gray potion effect
        default: op
    VaporTrails.effect.potion.crimson:
        description: Allows user to use crimson potion effect
        default: op
    VaporTrails.effect.potion.cyan:
        description: Allows user to use cyan potion effect
        default: op
    VaporTrails.effect.potion.blue:
        description: Allows user to use blue potion effect
        default: op
    VaporTrails.effect.potion.*:
        description: Allows user to use all potion effects
        default: op
        children:
            VaporTrails.effect.potion.pink: true
            VaporTrails.effect.potion.aqua: true
            VaporTrails.effect.potion.gold: true
            VaporTrails.effect.potion.green: true
            VaporTrails.effect.potion.red: true
            VaporTrails.effect.potion.darkred: true
            VaporTrails.effect.potion.gray: true
            VaporTrails.effect.potion.crimson: true
            VaporTrails.effect.potion.cyan: true
            VaporTrails.effect.potion.blue: true
    VaporTrails.effect.*:
        description: Gives access to all VaporTrails effects
        children:
            VaporTrails.effect.smoke: true
            VaporTrails.effect.ender: true
            VaporTrails.effect.thunder: true
            VaporTrails.effect.tnt: true
            VaporTrails.effect.snow: true
            VaporTrails.effect.fire: true
            VaporTrails.effect.block: true
            VaporTrails.effect.shine: true
            VaporTrails.effect.potion.*: true
        default: op
